# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e4be61ebab48eacba0b1960547bb55985cd3df314fee79325dc7bb48d32214c4c886fb6180b36e652272759a7bbb879f7cea607dde8cb33fdefc649e0eca9c4c

test:
  secret_key_base: b016150822dee9be794e0e27c8c9ed2a1a6cbc7cb7e861cbefa4c26f60256a64d6ac74a273f783d6b51041aef000b0389aca5908ba1179803b941e0d48ae0814

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
